<?php

namespace App\Filament\Resources\SmartCollectionResource\Pages;

use App\Filament\Resources\SmartCollectionResource;
use Filament\Resources\Pages\CreateRecord;

class CreateSmartCollection extends CreateRecord
{
    protected static string $resource = SmartCollectionResource::class;

    protected function getHeaderActions(): array
    {
        return [

        ];
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
